version: '3.1'

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: mongodb-bike-container
    ports:
      - 27017:27017
    networks:
      - bikenetwork
    volumes:
      - database-data:/data/db
    
  
  # Go Backend Service
  backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: bike-backend-container
    ports:
      - "9090:9090"
    depends_on:
      - mongodb
    networks:
      - bikenetwork

networks:
  bikenetwork:
    driver: bridge

volumes:
  database-data:
    driver: local

